apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nore-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nore-app 
  name: nore-app
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nore-app 
